### ISSUE TITLE
Libre.fm support

### ISSUE THREAD

**Issue by MunifTanjim** [Arkq/cmusfm#10]
Is there any plan for supporting [Libre.fm](https://libre.fm)?

**Comment by Arkq** [comment]
I've tried to find some libre.fm API documentation, however it seems, that there is none...

On the libre.fm wiki, I've found that the API is supposed to be compatible with the last.fm one. You can try to change `SCROBBLER_URL` and `SCROBBLER_USERAUTH_URL` definitions in the [src/libscrobbler2.h](https://github.com/Arkq/cmusfm/blob/master/src/libscrobbler2.h) file (if you know the URL for the libre.fm API) and see if the wiki is right.

I'm not a libre.fm user, so without any documentation there is very little to zero chances, that the libre.fm will be supported in the future.

**Comment by MunifTanjim** [comment]
Is this what you need?

- [Librefm API methods](https://git.gnu.io/foocorp/librefm/wikis/Librefm_API_methods)

- https://libre.fm/api/auth

- http://libre.fm/2.0

**Comment by Arkq** [comment]
Yeah, these links are more than enough. I had to be blind, not to spot this wiki page...

It seems, that the API is indeed compatible with last.fm. If there will be no further obstacles, I will try to add configuration for libre.fm.

Many thanks for these links.

**Comment by MunifTanjim** [comment]
Eagerly waiting for it :smile:

And thanks for creating and maintaining `cmusfm` :+1:

**Comment by Arkq** [comment]
Now you should be able to change scrobbling service from last.fm to libre.fm. See the [configuration](https://github.com/Arkq/cmusfm#configuration) section in the README file for more information.

**Comment by fwiep** [comment]
@Arkq, thank you for developing this scrobbler and adding Libre.fm support. I cloned the most recent version and installed it according to your instructions. Performed an "init" command, then edited the config URLs to point to Libre.fm. Now when I perform a second "init", it gives me `Error: API: Unknown error`.

@MunifTanjim, did you succeed in linking cmus to Libre.fm? How did you authenticate?

Can anyone help me, please?

Thanks,
Frans-Willem

**Comment by fwiep** [comment]
I seem to have found my own answer. On [this Japanese site](http://d.hatena.ne.jp/sonota88/20151116/1447684370), the Libre.fm authentication seems to be explained quite nicely. The first few steps have succeeded already (thanks to an online translator :) ).

Will go and build on this information.
Thanks,
Frans-Willem
