### ISSUE TITLE
Stops scrobbling if a single track's playing on repeat

### ISSUE THREAD

**Issue by MunifTanjim** [Arkq/cmusfm#11]
cmus has a **repeat current** option that's activated by pressing `[CTRL]+[R]`.

When it's activated, scrobbling is totally stopped. The track isn't even appended to the `cmusfm.cache` when the track finishes (and starts again).

**Comment by Arkq** [comment]
I've just checked this "repeat current" case, and unfortunately, it is not possible to fix it (not in the cmusfm). When a single track is repeated, cmus (I'm using v2.8.0-rc0) does not generate status event (dunno if it's a bug or feature)...

You may report this issue on the cmus project, though.

**Comment by MunifTanjim** [comment]
Created an issue cmus/cmus#711

**Comment by MunifTanjim** [comment]
It should work now! :smiley: cmus/cmus#712
