### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by schvabodka-man** [Arkq/cmusfm#12]
Hi there. Attempting to build cmusfm and getting these

syntax error near unexpected token `LIBCRYPTO,'
../configure: line 4163: `	PKG_CHECK_MODULES(LIBCRYPTO, libcrypto)

**Comment by Arkq** [comment]
If Internet is right, you need pkg-config to be installed prior to running configuration script. I've just added check for this requirement, so the error message will be more meaningful.
