### ISSUE TITLE
Problem with 'libcur' on installation?

### ISSUE THREAD

**Issue by noersetiawan** [Arkq/cmusfm#14]
Hi, I'm trying to install this but stuck on the third part:
`$ ../configure --enable-libnotify`
The error message is as follow:

> checking for LIBCRYPTO... yes
checking for LIBCURL... no
configure: error: Package requirements (libcurl) were not met:

> No package 'libcurl' found

> Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

>Alternatively, you may set the environment variables LIBCURL_CFLAGS
and LIBCURL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

However, I've checked that libcurl3 is installed, and there is no package simply called `libcurl`.
System is Ubuntu 16.04. Any help is appreciated.

EDIT: solved by installing libcurl4-gnutls-dev and libnotify-dev.

**Comment by Arkq** [comment]
OK, great you've worked that out. I'm closing this issue then.
