### ISSUE TITLE
Prefer %albumartist% over %artist%

### ISSUE THREAD

**Issue by budkin** [Arkq/cmusfm#16]
Can you please make this option in config? If there's a way to configure this in cmus settings, can you please point me in the right direction?

I see these formatting options: 
```
 format_current
 format_playlist
 format_playlist_va
 format_statusline
 format_title
 format_trackwin
 format_trackwin_album
 format_trackwin_va
 format_treewin
 format_treewin_artist
```

which one does cmusfm rely on?

**Comment by Arkq** [comment]
Hi, I've just pushed changes which will allow to scrobble *albumartist* ID3 tag. However, this will work only with `cmus` compiled from fresh master snapshot ([this commit](https://github.com/cmus/cmus/commit/4df336aa866a43c91a129ca92c0b277b338287c6) is required).

> which one does cmusfm rely on?

Cmusfm does not rely on any of these options. Cmusfm uses its own configuration, and to be quite honest it is not the best idea to allow user to prefer *albumartist* over *artist* or the other way around. *Albumartist* ID3 tag has well defined meaning, and it is supported by [the last.fm API](https://www.last.fm/api/show/track.scrobble).

Please, check if logic in the current master of `cmusfm` (and current master of `cmus`) meets your expectations :).
