### ISSUE TITLE
Scrobbling Björk specifically doesn't work.

### ISSUE THREAD

**Issue by sunnaryt** [Arkq/cmusfm#17]
I have a pretty extensive library including Japanese music that scrobbles fine. The only thing I have an issue with is Björk, in which case nothing happens at all.
The same music works in iTunes.

**Comment by Arkq** [comment]
Could you post somewhere the file which does not work?

**Comment by sunnaryt** [comment]
Unfortunately this would be illegal, is there something else I can do?

**Comment by Arkq** [comment]
> Unfortunately this would be illegal

yeap :/

OK, I know what you can do. In this repo there is a file [cmusfm.debug](https://github.com/Arkq/cmusfm/blob/master/cmusfm.debug). Use this file as a scrobbler (it dumps metadata exposed by the cmus) and post here generated `/tmp/cmusfm.debug` file.

**Comment by sunnaryt** [comment]
Sure, looking over the log it created it seems as though it doesn't see an artist.

[cmusfm.debug.txt](https://github.com/Arkq/cmusfm/files/1805135/cmusfm.debug.txt)

Here's metadata on one of the files in the album through this website I found(the first one logged): 
https://www.get-metadata.com/result/1abf7898-534d-46e4-8a82-0a83919f0c9a

Cmus as well detects the artist as normal.

**Comment by Arkq** [comment]
> Looking over the log it created it seems as though it doesn't see an artist.

Yes, you're right. However, there is nothing I can do about this. Lines stored in the cmusfm.debug file depict `cmusfm` invocation by `cmus`. Apparently, `cmus` does not expose artist for these two affected files. What concerns me, is the fact, that the file path does not contain artist name as well:

Music/(2001) Vespertine/Hidden Place.mp3
vs
Music/Black Marble - It's Immaterial (2016)/01 Interdiction.mp3

Are you sure, that `cmus` detects artist tag correctly? Maybe it is not a standard "artist" tag. Check, in which tag artist is stored for other files. Anyway, this issue should be reported for [cmus](https://github.com/cmus/cmus/issues) - it's not a `cmusfm` bug.

**Comment by Arkq** [comment]
It seems, that in the next `cmus` release, album artist will be exposed to the status program: https://github.com/cmus/cmus/commit/4df336aa866a43c91a129ca92c0b277b338287c6

I will make required changes to the `cmusfm`. This change will be according to the issue #16, so if album artist will be present, it will be preferred.

**Comment by Arkq** [comment]
Please check current master snapshot of `cmusfm` with `cmus` compiled from **fresh** [master](https://github.com/cmus/cmus/tree/master) branch.
