### ISSUE TITLE
Failing to scrobble from an internet stream

### ISSUE THREAD

**Issue by YuyQuan** [Arkq/cmusfm#22]
![image](https://user-images.githubusercontent.com/15720568/46708966-0bd2c580-cc07-11e8-9dbb-0ba021974905.png)

Local files work just fine, but cmusfm fails to report something that is currently playing from an internet stream.

**Comment by Arkq** [comment]
Many thanks for reporting, and please let me know if the fix works for you.

**Comment by YuyQuan** [comment]
Yes! It works! You are my hero.

![screen shot 2018-10-11 at 11 52 18 am](https://user-images.githubusercontent.com/15720568/46820644-5578f880-cd4c-11e8-8c67-49e2d539abb8.png)
