### ISSUE TITLE
Build isn't finishing

### ISSUE THREAD

**Issue by nbruner04** [Arkq/cmusfm#23]
When trying to build, it stopped early and it came up with some errors. 
`/bin/mkdir -p '/usr/local/bin'
 /usr/bin/install -c cmusfm '/usr/local/bin'
/usr/bin/install: cannot create regular file '/usr/local/bin/cmusfm': Permission denied
Makefile:314: recipe for target 'install-binPROGRAMS' failed
make[2]: *** [install-binPROGRAMS] Error 1
make[2]: Leaving directory '/home/nathan/cmusfm/build/src'
Makefile:583: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/nathan/cmusfm/build/src'
Makefile:363: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
`
To be honest I'm a complete newb to Linux, and I don't know how to fix the problem from the info that is being provided. If anyone here can tell me how to fix the problem, it would be greatly appreciated.
Thanks.

**Comment by Arkq** [comment]
For installation you need `root` permission. Try something like: `sudo make install`.

**Comment by nbruner04** [comment]
Thank you

**Comment by blackdead263** [comment]
I had `cmusfm` working on my old laptop and now that i want to use it on another one i get this error.
I do use `sudo` but it's still the same.


```
>> sudo make && make install

make  all-recursive
make[1]: Entering directory '/home/nitwit/cmusfm/build'
Making all in src
make[2]: Entering directory '/home/nitwit/cmusfm/build/src'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/nitwit/cmusfm/build/src'
Making all in test
make[2]: Entering directory '/home/nitwit/cmusfm/build/test'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/nitwit/cmusfm/build/test'
make[2]: Entering directory '/home/nitwit/cmusfm/build'
make[2]: Leaving directory '/home/nitwit/cmusfm/build'
make[1]: Leaving directory '/home/nitwit/cmusfm/build'
Making install in src
make[1]: Entering directory '/home/nitwit/cmusfm/build/src'
make[2]: Entering directory '/home/nitwit/cmusfm/build/src'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c cmusfm '/usr/local/bin'
/usr/bin/install: cannot remove '/usr/local/bin/cmusfm': Permission denied
Makefile:314: recipe for target 'install-binPROGRAMS' failed
make[2]: *** [install-binPROGRAMS] Error 1
make[2]: Leaving directory '/home/nitwit/cmusfm/build/src'
Makefile:583: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/nitwit/cmusfm/build/src'
Makefile:363: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

**Comment by Arkq** [comment]
Try to kill already running instance of cmusfm, because it might lock its
exec, so install fails with permission denied error.

**Comment by blackdead263** [comment]
I guess I just ignored the error and ran `cmusfm` as a command and it worked! thanks.
