### ISSUE TITLE
pkg-config is required

### ISSUE THREAD

**Issue by zjquid** [Arkq/cmusfm#24]
(macos) I've installed pkg-config using homebrew, but when running ../configure --enable-libnotify it returns with a long list of "checking" processes and finally "configure: error: pkg-config is required. See pkg-config.freedesktop.org". How do I make my computer know I've installed pkg-config? 
I'm extremely new to this, I'm sorry if this is a waste of time. Google has yielded no helpful results

**Comment by blackdead263** [comment]
try `libnotify-dev`

**Comment by Arkq** [comment]
If anyone stumbles upon this issue, here is the answer. The `pkg-config` has to be installed *BEFORE* running `autoreconf --install`. If you've instilled it after that, you have to rerun autoreconf.
