### ISSUE TITLE
Can't get any last.fm authorization

### ISSUE THREAD

**Issue by cataclisma117** [Arkq/cmusfm#25]
Hello. My cmusfm can't get any link to authorize scrobbling to last.fm. Here is what happens:

Checking previous session (user: *******) ...failed.
Fetch new session key [yes/NO]: yes
Error: Problem with the SSL CA cert (path? access rights?)

Is it a problem with cmusfm or with my installation? Because I searched and I found nothing about that. Looks like my cmusfm is running fine, expect for that, because I turned on the notifications and it's working.
That's why I made this issue, because must be something with last.fm authentication or related.
Thanks.

**Comment by Arkq** [comment]
There has to be something wrong with your libcurl installation, I think. If this issue still occurs, please reopen it.
