### ISSUE TITLE
cmusfm server process will not start if resume=true in cmus

### ISSUE THREAD

**Issue by icesoldier** [Arkq/cmusfm#3]
Currently it looks like cmusfm will only start its server process if it receives a status update that doesn't include a filename of some kind. However, if the "resume" setting is set in cmus, it will send a "paused" status on launch with the file that was playing when cmus was closed last. Because of this, upon a reboot or when the cmusfm server process is killed, no submission will be sent or even cached.

I currently have a workaround set up involving using a [wrapper script][1] that will start cmusfm with a fake stopped status if it's not running prior to running cmusfm with the proper status update, and pointing cmus' status_display_program at that script.

[1]: https://gist.github.com/icesoldier/5bcfb86276417c900060

**Comment by Arkq** [comment]
Many thanks for reporting it!
Funny thing is, that I've spotted this bug 3 days ago, but I was too lazy to fix it right away.
