### ISSUE TITLE
Manjaro dont' working

### ISSUE THREAD

**Issue by amoksito** [Arkq/cmusfm#31]
Cmusfm does not seems to be working for me. I'm in Manjaro Linux ... Is a problem with my sistem or something change in the api or something? How can I debug this?

Thks in advance!

**Comment by Arkq** [comment]
What says `cmusfm init`? You can compile cmusfm with `--enable-debug`, there will be some extra info available, maybe it will give you a hint.

In terminal run:
```
pkill cmusfm
cmusfm server
```

Then start to scrobble. This way you should see debug information from the server.

**Comment by amoksito** [comment]
Thanks! Now it is working.
