### ISSUE TITLE
libcurl.so.4: version `CURL_OPENSSL_3' not found

### ISSUE THREAD

**Issue by mamafanfan** [Arkq/cmusfm#35]
fail to exec `cmusfm init`. it returns the above error.

> dim@moonwalk:\~$ cmus \-\-version
>  cmus v2.8.0
    Copyright 2004-2006 Timo Hirvonen
    Copyright 2008-2016 Various Authors
> dim@moonwalk:\~$ curl \-\-version
> curl 7.72.0 (x86_64-pc-linux-gnu) libcurl/7.72.0 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5)  
    libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
    Release-Date: 2020-08-19
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet   
    tftp 
> Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL > TLS-SRP UnixSockets
> dim@moonwalk:\~$ cmusfm init
    cmusfm: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by cmusfm)

```
OS: Debian GNU/Linux 10 (buster) x86_64 
Kernel: 5.7.0-0.bpo.2-amd64 
```

No errors were detected during build. All went smoothly.

**Comment by mamafanfan** [comment]
answer to myself.

I need to `sudo make install`. problem solved.

**Comment by Arkq** [comment]
Glad you've managed to resolve this issue :)
