### ISSUE TITLE
Checking previous session (user: User) ...failed.

### ISSUE THREAD

**Issue by 9Labbs** [Arkq/cmusfm#41]
**Cmusfm is not working even when I gave it access to last.fm**
This never happened before. Any idea of what could be the _problem_? I tried **deleting** the file and **giving** it **permissions again**. I've tried everything but _it is not working_.

When I run `cmusfm init` to see if it's working, I get this:
```
Checking previous session (user: Fenneko666) ...failed.
Fetch new session key [yes/NO]: no
```

But when I look at my Applications Settings in Last FM, cmusfm is there as all my other scrobblers that work.

**Comment by Arkq** [comment]
Please check current master branch.

_Note: This is a duplicate of #40_
