### ISSUE TITLE
Doubt about installing cmusfm

### ISSUE THREAD

**Issue by erlonpr** [Arkq/cmusfm#44]
First, I would like to congratulate you for the great idea to develop a plugin that integrates cmus with Lastfm.

But back to what matters...
I'm getting in touch as I recently discovered the cmus audio player and I'm still learning how to use it. Also, I really enjoy scrobbling the songs I listen to locally with my Lastfm profile.

Based on that, I would like to integrate the cmus with my Lastfm, but I am not able to understand how I can install the cmusfm.

Could you post a step by step how to correctly install cmusfm?

**Comment by erlonpr** [comment]
I'm trying to install cmusfm on Ubuntu 20.04.

**Comment by Arkq** [comment]
Simply follow the "Installation" section from the README file. For required dependencies see this: https://github.com/Arkq/cmusfm/blob/master/.github/workflows/build-and-test.yaml#L19
