### ISSUE TITLE
100% CPU on cmusfm stop

### ISSUE THREAD

**Issue by mederel** [Arkq/cmusfm#5]
Hi,

sometimes, and I have hard time figuring out when, cmusfm runs with a 100% CPU and never stops. I have to do a kill -15 <pid> for it to stop.

I would like to give you tangible information. Thing is I am not well versed enough in cmus and cmusfm to actually find the right logs/measures... Would you know what I can do to figure this out?

BTW it might have nothing to do with cmusfm...

What I am using:
cmusfm 0.2.5, built with libnotify support
cmus 2.5.0
libnotify 0.7.6
desktop env: plasma 5.4.2

Thanks in advance!

**Comment by mederel** [comment]
Or maybe it is because I am using the latest release and not the latest snapshot? (I see there has been a lot of commits since last release).

In which case I will create a live version of the ebuild on Gentoo.

**Comment by Arkq** [comment]
Hi,

I will try to check few things which might cause such an issue. However, it might not be easy... It would be very helpful if you could provide some traceback. If you ever encounter this problem again, try to attach to this process with gdb (prior to this compile cmusfm with "-g" flag), e.g.:

    gdb -p $(pgrep cmusfm)

and backtrace (`bt`) until some cmusfm component appears.

As for master snapshot. Currently, there is only one minor issue fixed (other commits are just polishing and code style enhancements), so I've postponed creating new release until something bigger occurs :).

**Comment by mederel** [comment]
Hi,
thank you for your quick answer. I will try to debug and try to get that backtrace for you.
I will also try to run cmus 2.7.1 to see if that fixes the issue.
Will keep you up to date.
Thanks and have a nice week.

**Comment by Arkq** [comment]
I'm going to close this issue for now. It's been a long time, and I see no feedback (I hope, that everything is working fine). Anyway, the version v0.2.5 is rather far behind the current master snapshot - a lot of "unstable" code (in my opinion) has been rewritten, so there is a great chance that the bug has been exterminated as well :D.
