### ISSUE TITLE
cmusfm auth error

### ISSUE THREAD

**Issue by t-recx** [Arkq/cmusfm#9]
Hi, I recently installed cmusfm and it didn't scrobble to last.fm.
Enabling debug on configure and running cmusfm server on the command line yielded: 
...
DEBUG ../../src/libscrobbler2.c:112: check: status: 0, body: 
`<?xml version="1.0" encoding="utf-8"?>
<lfm status="failed">
  <error code="9">Invalid session key - Please re-authenticate</error>
</lfm>`
...
Retried cmusfm init a couple more times, .config/cmus/cmusfm.conf updated accordingly. 
Any ideas? I tried looking for the last.fm app/keys page on the user settings to check if there was anything wrong with the key, but couldn't find it.

Thanks

**Comment by Arkq** [comment]
Thanks for making this issue. It seems, that last.fm has made some changes in the authentication process, but this change affects new users only, so I did not see this issue by myself.

**Comment by t-recx** [comment]
It's working now, thanks again <3
